In [1]:
import pandas as pd
import numpy as np

In [6]:
M = pd.read_csv("Movie Reviews.csv", index_col='Name')

In [7]:
M.head()

,American Sniper,The Hunger Games: Mockingjay - Part 1,Guardians of the Galaxy,The Lego Movie,The Hobbit,Transformers,Malificent,Big Hero 6,Godzilla,Interstellar,How to Train your Dragon 2,Gone Girl,Divergent,The Fault in Our Stars,Unbroken,300: Rise of an Empire
Name,,,,,,,,,,,,,,,,
Mike,NaN,NaN,5,NaN,4,NaN,3,NaN,NaN,NaN,NaN,NaN,3,NaN,NaN,2
HJ SONG,NaN,2,3,4,4,5,NaN,4,4,5,5,NaN,NaN,NaN,5,5
Ryan Hansen,NaN,3,4,3,5,2,3,3,3,NaN,5,NaN,3,NaN,NaN,NaN
Olumuyiwa Durojaiye,NaN,NaN,NaN,NaN,NaN,5,NaN,5,2,NaN,3,NaN,NaN,NaN,NaN,2
Charlie,NaN,2,3,NaN,3,2,3,NaN,4,5,2,NaN,2,3,NaN,2

In [8]:
def pearson(s1, s2):
    """Take two pd.Series objects and return a pearson correlation."""
    s1_c = s1 - s1.mean()
    s2_c = s2 - s2.mean()
    return np.sum(s1_c * s2_c) / np.sqrt(np.sum(s1_c ** 2) * np.sum(s2_c ** 2))

In [9]:
M.shape

(31, 16)

In [10]:
def get_recs(movie_name, M, num):

    import numpy as np
    reviews = []
    for title in M.columns:
        if title == movie_name:
            continue
        cor = pearson(M[movie_name], M[title])
        if np.isnan(cor):
            continue
        else:
            reviews.append((title, cor))
    
    reviews.sort(key=lambda tup: tup[1], reverse=True)
    return reviews[:num]

###Question 1:  What movie is most Similar to 'The fault in our stars'

In [11]:
recs = get_recs('The Fault in Our Stars', M, 10)

In [12]:
recs[:1]

[('Transformers', 0.46673568990261)]

###Question 2:  Which movie(s) would you most like to see, based on your classmates experience?

In [14]:
#the movies which I've seen
my_ratings = M.ix['Aswini kumar'].dropna()

In [15]:
#the movies which I've rated the highest
my_ratings.sort(ascending=False)
max=my_ratings.values[0]
fav_movies=my_ratings[my_ratings==max]

In [16]:
fav_movies

Interstellar               5
Big Hero 6                 5
Guardians of the Galaxy    5
Name: Aswini kumar, dtype: float64

In [17]:
#based on my classmates experience the movie I would like to see 
for i in range(len(fav_movies)):
         recs = get_recs(fav_movies.index[i], M, 10)
         print recs[:1]

[('The Lego Movie', 0.46574538914196745)]
[('Transformers', 0.45293471081198539)]
[('The Hunger Games: Mockingjay - Part 1', 0.67851374100065553)]

###Question 3: Bonus Question...  For all the movies you haven't seen, can you predict how you'd rate them using your the class reviews?

In [18]:
df1=M.fillna(0)
df1[df1 != 0] = 1
df1

,American Sniper,The Hunger Games: Mockingjay - Part 1,Guardians of the Galaxy,The Lego Movie,The Hobbit,Transformers,Malificent,Big Hero 6,Godzilla,Interstellar,How to Train your Dragon 2,Gone Girl,Divergent,The Fault in Our Stars,Unbroken,300: Rise of an Empire
Name,,,,,,,,,,,,,,,,
Mike,0,0,1,0,1,0,1,0,0,0,0,0,1,0,0,1
HJ SONG,0,1,1,1,1,1,0,1,1,1,1,0,0,0,1,1
Ryan Hansen,0,1,1,1,1,1,1,1,1,0,1,0,1,0,0,0
Olumuyiwa Durojaiye,0,0,0,0,0,1,0,1,1,0,1,0,0,0,0,1
Charlie,0,1,1,0,1,1,1,0,1,1,1,0,1,1,0,1
Sina Tuy,0,1,1,1,1,1,1,1,1,0,1,1,1,1,0,1
Pavithra Shetty,0,1,0,0,1,1,0,0,0,0,1,0,0,0,0,0
Sara Collins,0,1,1,0,0,0,1,0,0,0,0,0,0,1,0,0
Jonathan Doll,0,1,0,1,1,1,0,0,0,0,1,0,0,0,0,0
saikiran reddy,1,1,1,0,1,1,1,0,1,1,1,1,1,1,0,1
Aishwarya reddy,0,1,1,1,1,1,1,0,1,1,1,1,0,1,0,1
Brant Mullinix,0,1,1,1,1,1,0,0,0,1,1,1,0,0,0,1
Sai Sampath,0,1,1,1,1,1,1,0,1,1,1,1,0,1,0,1
Suyendra,0,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1
Sai Yallapragada,1,1,1,1,0,1,0,0,1,1,0,0,1,0,0,1
Akhilesh,0,0,1,1,1,1,0,0,0,1,0,1,0,0,0,1
Sundar Prasad,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1
Evan Piercy,1,0,0,1,0,1,0,0,0,1,0,1,0,0,0,1
Jessica Fong,0,1,1,0,0,1,0,0,0,1,0,0,1,0,0,0
Onsiri Tapsarn,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
Anirudh Thota,0,1,1,1,1,1,0,0,1,1,1,0,0,0,0,1
Greg Werner,1,1,1,0,0,1,1,0,0,1,1,1,1,0,0,1
Violeta Lee Fay,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,1
Aditya Dharmasagar,1,0,0,1,1,1,1,0,1,1,1,1,1,1,0,1
Manideep Maddipatla,1,1,1,1,1,1,0,1,1,1,1,0,1,0,1,1
Maheshwar Reddy,1,1,1,0,1,1,0,1,0,1,0,1,0,0,0,1
siddanth sudarshan,1,1,1,0,1,0,0,0,0,1,0,1,0,0,0,1
anurag,1,0,0,0,1,0,0,0,1,0,1,0,1,0,0,1
Ahmed Muheebuddin,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0
azam,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0
Aswini kumar,1,1,1,0,0,0,0,1,1,1,1,0,0,0,0,1

In [19]:
co_occurence = df1.T.dot(df1) 
co_occurence

,American Sniper,The Hunger Games: Mockingjay - Part 1,Guardians of the Galaxy,The Lego Movie,The Hobbit,Transformers,Malificent,Big Hero 6,Godzilla,Interstellar,How to Train your Dragon 2,Gone Girl,Divergent,The Fault in Our Stars,Unbroken,300: Rise of an Empire
American Sniper,13,7,9,4,8,7,3,3,6,9,6,7,6,2,1,10
The Hunger Games: Mockingjay - Part 1,7,20,18,11,15,17,9,7,12,14,15,8,9,7,3,15
Guardians of the Galaxy,9,18,22,11,17,16,10,7,12,15,13,9,10,7,3,17
The Lego Movie,4,11,11,14,12,14,6,5,10,10,11,7,6,5,3,12
The Hobbit,8,15,17,12,21,16,9,6,12,12,15,9,9,7,3,16
Transformers,7,17,16,14,16,23,9,7,15,15,17,10,10,7,3,19
Malificent,3,9,10,6,9,9,11,3,8,6,9,6,8,8,1,9
Big Hero 6,3,7,7,5,6,7,3,8,7,4,7,2,4,2,3,7
Godzilla,6,12,12,10,12,15,8,7,17,10,15,5,9,7,3,16
Interstellar,9,14,15,10,12,15,6,4,10,17,11,10,7,5,2,16
How to Train your Dragon 2,6,15,13,11,15,17,9,7,15,11,19,7,9,7,3,16
Gone Girl,7,8,9,7,9,10,6,2,5,10,7,12,4,5,0,11
Divergent,6,9,10,6,9,10,8,4,9,7,9,4,12,5,2,10
The Fault in Our Stars,2,7,7,5,7,7,8,2,7,5,7,5,5,8,1,7
Unbroken,1,3,3,3,3,3,1,3,3,2,3,0,2,1,3,3
300: Rise of an Empire,10,15,17,12,16,19,9,7,16,16,16,11,10,7,3,23

In [20]:
my_movie_ratings =M.ix['Aswini kumar'].fillna(0)

In [21]:
my_movie_ratings

American Sniper                          4
The Hunger Games: Mockingjay - Part 1    4
Guardians of the Galaxy                  5
The Lego Movie                           0
The Hobbit                               0
Transformers                             0
Malificent                               0
Big Hero 6                               5
Godzilla                                 3
Interstellar                             5
How to Train your Dragon 2               4
Gone Girl                                0
Divergent                                0
The Fault in Our Stars                   0
Unbroken                                 0
300: Rise of an Empire                   4
Name: Aswini kumar, dtype: float64

In [22]:
my_predicted_ratings = co_occurence.dot(my_movie_ratings)
my_predicted_ratings

American Sniper                          267
The Hunger Games: Mockingjay - Part 1    459
Guardians of the Galaxy                  484
The Lego Movie                           312
The Hobbit                               427
Transformers                             475
Malificent                               239
Big Hero 6                               212
Godzilla                                 392
Interstellar                             410
How to Train your Dragon 2               424
Gone Girl                                252
Divergent                                268
The Fault in Our Stars                   183
Unbroken                                  89
300: Rise of an Empire                   504
dtype: float64